In [3]:
import pandas as pd

pd.read_parquet('hyperliquid_orderbook.parquet')

,timestamp,hl_best_bid_px,hl_best_bid_sz,hl_best_ask_px,hl_best_ask_sz
0,2025-12-03 18:14:25.273601,3058.0,313.5135,3058.1,0.1252
1,2025-12-03 18:14:25.375351,3058.0,313.5135,3058.1,0.1252
2,2025-12-03 18:14:25.480480,3058.0,313.5135,3058.1,0.1252
3,2025-12-03 18:14:25.585163,3058.0,313.5135,3058.1,0.1252
4,2025-12-03 18:14:25.690289,3058.0,484.8655,3058.2,0.0930
...,...,...,...,...,...
9295,2025-12-03 18:30:40.739322,3065.3,65.2960,3065.4,248.2309
9296,2025-12-03 18:30:40.844106,3065.3,65.2960,3065.4,248.2309
9297,2025-12-03 18:30:40.949214,3065.3,65.2960,3065.4,248.2309
9298,2025-12-03 18:30:41.051694,3065.3,65.2960,3065.4,248.2309
9299,2025-12-03 18:30:41.153184,3065.3,65.2960,3065.4,248.2309

In [2]:
pd.read_parquet('binance_orderbook.parquet')

,timestamp,bin_best_bid_px,bin_best_bid_sz,bin_best_ask_px,bin_best_ask_sz
0,2025-12-03 16:12:44.922054,3058.17,19.6767,3058.18,23.6728
1,2025-12-03 16:12:45.025947,3058.17,19.6767,3058.18,23.6755
2,2025-12-03 16:12:45.126155,3058.17,19.6767,3058.18,23.6755
3,2025-12-03 16:12:45.220605,3058.17,19.6767,3058.18,23.6755
4,2025-12-03 16:12:45.323131,3058.17,19.6767,3058.18,23.6755
...,...,...,...,...,...
10495,2025-12-03 16:30:31.164808,3050.64,29.5188,3050.65,34.0905
10496,2025-12-03 16:30:31.165448,3050.64,26.2916,3050.65,37.3177
10497,2025-12-03 16:30:31.165882,3050.64,22.7519,3050.65,37.3177
10498,2025-12-03 16:30:31.166274,3050.64,24.4793,3050.65,37.3177
10499,2025-12-03 16:30:31.166649,3050.64,18.4005,3050.65,37.3177

In [ ]:
pd.read_parquet('paradex_orderbook.parquet')